version: "3.5"

services:
  app:
    build: .
    container_name: app_grpc_server
    volumes:
      - .:/go/src/
    ports:
      - 8000:8000
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
